# Use official Node.js image
FROM node:22

# Set working directory
WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

RUN rm -rf ./src

# Expose the application port
EXPOSE 3002

# Start the application
CMD ["npm", "run", "start:prod"]
